### ISSUE TITLE
understanding open_fs

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/webdavfs#13]
I thought about to add a password dialog to my application, because I wanted to split the login information from that fs_url string. I tried to use `parse_result` data for `open_fs` but this gives no login.

It looks to me that `parse_result` is always a dependency from `fs_url.` So for example if my `fs_url` has `login:password` this is then parsed to `parse_result`. If I add myself `parse_result` and have no login information in the `fs_url`, then `parse_result` entries are None for username and password.

The decription looks like it can may be a seperate parameter.
http://pyfilesystem2.readthedocs.io/en/latest/reference/opener.html?highlight=open_fs
`open_fs(fs_url, parse_result, writeable, create, cwd)`

I don't know if that is a problem here or somewhere underlaying.

**Comment by willmcgugan** [comment]
That particular method is called by the `Registry` object. It's not really intended as a public interface.

I gather you want to be able to supply a pre-created `ParseResult` instance, rather than a FS URL when opening a filesystem? That's not directly supported at the moment. You could just create a FS URL with the username + password by concatenating the strings.

**Comment by willmcgugan** [comment]
Just realised this was in webdavfs. If its purely webdav you need, you can construct a `WebDavFS` manually (see https://github.com/PyFilesystem/webdavfs/blob/master/webdavfs/webdavfs.py#L158).

**Comment by ReimarBauer** [comment]
I posted it here because my current example I found this was by webdavfs. I have the same later for ftp and ssh. Ok, constructing will also work with the others.  That's simple enough :)
